global:
  # steampipeDatabasePassword will be used to set the Steampipe DB password
  # and powerpipe DB Connection URL will get this value from here 
  steampipeDatabasePassword: "Kj8mP2vN9xQ7tR5wL3cY1hB4nM6sD0pF"
  # Enable to have Read Only access to the deployed cluster 
  steampipeCreateReadOnlyServiceAccount: true



steampipe:
  # Additional Secret Env Vars for steampipe
  secretEnvVars: {}

  # Define non-secret Env Vars for steampipe
  envVars:
    # INSTALL_PLUGINS will install steampipe plugins at runtime.
    #   Note: INSTALL_PLUGINS env. var. should be space separated
    # Take look at available plugins: https://hub.steampipe.io/
    # INSTALL_PLUGINS: "steampipe kubernetes aws"

    # following yaml syntax (>) will merge newlines with spaces
    INSTALL_PLUGINS: >
      kubernetes
    
    # set the default aws profile if you are passing aws credentials, or use .spc files
    # AWS_PROFILE: "default" 


  # secretCredentials will create Secret and
  # will put the file content to  '~/{directory}/{filename}'
  # useful for passing aws, gcp, kubeconfig credentials
  secretCredentials: {}
    # - name: kubeconfig  
    #   directory: ".kube"
    #   filename: "config"
    #   content: |
    #     example kubeconfig


  # .config is used to create a ConfigMap
  # and will be mounted to ~/.steampipe/config/{key} — the filename being the key  
  # use it to configure steampipe: https://steampipe.io/docs/reference/config-files/overview
  config: {}
    # kubernetes.spc: |
    #   connection "kubernetes" {
    #     plugin         = "kubernetes"
    #     config_path    = "~/.kube/config"
    #     config_context = "myCluster"
    #     source_types   = ["deployed"]
    #   }

  initDbSqlScripts: {}

  replicaCount: 1
  containerPort: 9193
  image:
    repository: ghcr.io/oguzhan-yilmaz/kdiff-snapshots
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.

  imagePullSecrets: []
  nameOverride: "kdiff-snapshots"
  fullnameOverride: "kdiff-snapshots"

  podAnnotations: {}

  podSecurityContext:    
    fsGroup: 11234

  securityContext:
    runAsUser: 11234
    runAsGroup: 11234
    runAsNonRoot: true

  service:
    type: ClusterIP
    port: 9193

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
