{{- if and .Values.serviceAccount.awsIrsa.enabled .Values.serviceAccount.awsIrsa.additionalPolicyArns }}
{{- range $policyArn := .Values.serviceAccount.awsIrsa.additionalPolicyArns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kdiff-snapshots.fullname" $ }}-policy-{{ $policyArn | replace "arn:aws:iam::" "" | replace ":" "-" | replace "/" "-" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kdiff-snapshots.labels" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kdiff-snapshots.fullname" $ }}-policy-binding-{{ $policyArn | replace "arn:aws:iam::" "" | replace ":" "-" | replace "/" "-" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kdiff-snapshots.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kdiff-snapshots.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kdiff-snapshots.fullname" $ }}-policy-{{ $policyArn | replace "arn:aws:iam::" "" | replace ":" "-" | replace "/" "-" | trunc 63 | trimSuffix "-" }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }} 