# every key: data here will be mounted to ./steampipe/config/* 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kdiff-snapshots.fullname" . }}-config
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
{{- if eq (len (.Values.steampipe.config | default (dict))) 0 }}
data: {}
{{- else }}
data: {{ toYaml .Values.steampipe.config | nindent 2 }}
{{- end }}
