apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kdiff-snapshots.fullname" . }}
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.steampipe.replicaCount }}
  selector:
    matchLabels:
      {{- include "kdiff-snapshots.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.steampipe.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kdiff-snapshots.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.steampipe.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: true
      serviceAccountName: {{ include "kdiff-snapshots.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.steampipe.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "kdiff-snapshots.fullname" . }}
          envFrom:
          - configMapRef:
              name: {{ include "kdiff-snapshots.fullname" . }}-cm-env-vars
          - secretRef:
              name: {{ include "kdiff-snapshots.fullname" . }}-credentials
          securityContext:
            {{- toYaml .Values.steampipe.securityContext | nindent 12 }}
          image: "{{ .Values.steampipe.image.repository }}:{{ .Values.steampipe.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.steampipe.image.pullPolicy }}
          #command: ["sleep", "3000"]
          ports:
            - name: postgres
              containerPort: {{ .Values.steampipe.containerPort }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - bash
              - ./healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          {{- if .Values.steampipe.resources }}
          resources:
            {{- toYaml .Values.steampipe.resources | nindent 12 }}
          {{- else }}
          resources: {}
          {{- end }}
          {{- include "kdiff-snapshots.containerVolumeMounts" . | indent 10}}
      {{- include "kdiff-snapshots.containerVolumes" . | indent 6}}
      {{- with .Values.steampipe.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.steampipe.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.steampipe.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
