apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdiff-sa-role
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]  # All API groups
    resources: ["*"]  # All resources
    verbs: ["get", "list", "watch"]  # Read-only permissions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdiff-sa-role-binding
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kdiff-snapshots.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kdiff-sa-role
  apiGroup: rbac.authorization.k8s.io