apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kdiff-snapshots.fullname" . }}-steampipe-creds
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
{{- if eq (len (.Values.steampipeSecretCredentials | default (dict))) 0 }}
stringData: {}
{{- else }}
stringData:
{{- range $config := .Values.steampipeSecretCredentials }}
  {{ $config.name }}: | {{ $config.content | nindent 4}}
{{- end }}
{{- end }}

