{{- if and .Values.kdiffSecretEnvVars (not .Values.serviceAccount.awsIrsa.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kdiff-snapshots.fullname" . }}-secret-env-vars
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.kdiffSecretEnvVars | nindent 2 }}
{{- end }} 