apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kdiff-snapshots.fullname" . }}-secret-env-vars
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnvVars }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}