{{- if (.Values.serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdiff-snapshots.serviceAccountName" . }}
  labels:
    {{- include "kdiff-snapshots.labels" . | nindent 4 }}
  annotations:
    {{- with (.Values.serviceAccount).annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if (.Values.serviceAccount).awsIrsa.enabled }}
    eks.amazonaws.com/role-arn: {{ (.Values.serviceAccount).awsIrsa.roleArn | quote }}
    {{- end }}
{{- end }} 