name: Build and publish a docker images to ghcr.io

on:
  push:
    tags:
      - "v*.*.*"

# Prevent concurrent workflows for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-snapshots
  DOCKER_BUILDKIT: 1 # Enable BuildKit for better performance

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add timeout to prevent hanging workflows

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated from v3
        # with:
        #   fetch-depth: 0  # Fetch all history for better versioning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Added for better build performance

      - name: Log in to the Container registry
        uses: docker/login-action@v3 # Updated from v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Install jq
        run: |
          sudo apt-get update -y
          # Using apt-get instead of snap for better reliability
          sudo apt-get install -y jq

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kdiff-snapshots
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./kdiff-snapshots/Dockerfile
          cache-from: type=gha # Enable GitHub Actions cache
          cache-to: type=gha,mode=max
          provenance: true # Enable provenance attestation
          sbom: true # Enable SBOM generation
