name: Build and publish a docker images to ghcr.io

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

# Prevent concurrent workflows for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-snapshots
  # IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1 # Enable BuildKit for better performance

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add timeout to prevent hanging workflows

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated from v3
        # with:
        #   fetch-depth: 0  # Fetch all history for better versioning

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Added for better build performance

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metad
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./kdiff-snapshots
          # context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metad.outputs.tags }}
          labels: ${{ steps.metad.outputs.labels }}
          file: ./Dockerfile
          cache-from: type=gha # Enable GitHub Actions cache
          cache-to: type=gha,mode=max
          provenance: true # Enable provenance attestation
          sbom: true # Enable SBOM generation
